### ISSUE TITLE
URL error

### ISSUE THREAD

**Issue by sunhongyue4500** [spfrommer/terrain-elevation#1]
hi, i run your code, but the code can not download the data. the usgs terrain url seems to be something wrong.

**Comment by spfrommer** [comment]
Could you please post the code that's not working?

**Comment by spfrommer** [comment]
Hi @sunhongyue4500,
I've just run the example code and it seems to be working fine. The data files are quite large and can take 10-15 minutes to download. If waiting doesn't work please post more details about your problem and I'll have a look.
