### ISSUE TITLE
Constant RASTER_SIZE seems to cause very occasional errors

### ISSUE THREAD

**Issue by YaguangZhang** [spfrommer/terrain-elevation#2]
We encountered an error while taking advantage of this library in our project and we feel it is better to share it with you for the best fix. The snippet below will reproduce the error:

``` Matlab
latRange = [39.857760, 39.871599];
lonRange = [-84.840554, -84.822595];
region = fetchregion(latRange, lonRange, 'display', true);
rawElevData = region.readelevation(...
    latRange, lonRange, ...
    'sampleFactor', 1, ...
    'display', true);
```

And the corresponding output (produced in Matlab R2019a for both Windows and Linux) is:

```Matlab
-----Area n40w085-----
Downloading area
Extracting area
Reading elevation data 1,1
Unable to perform assignment because the size of the
left side is 10812-by-10812 and the size of the right
side is 10813-by-10813.

Error in Region/readelevation (line 104)
                    elev(sampleSize * (i - 1) + 1 :
                    sampleSize * i, ...
```

The error was caused because somehow the tile n40w085 has a 10813-by-10813 data size, which contradicts the hard-coded constant RASTER_SIZE = 10812 (line 39 in Region.m). It seems that the easiest way to deal with the anomaly is to truncate the data when necessary. What do you think?

By the way, thanks for creating such a convenient tool!

**Comment by spfrommer** [comment]
Thanks for the bug report -- fixed in #623aa3a .
